application:
  name: "call-events-service"

server:
  port: 8080

kafka:
  bootstrapAddress: "localhost:9092"
  callEventsTopicName: "events.TestEventV1"

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3308/new_base"
    username: root
    password: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
